tap "homebrew/bundle"

cask "1password"
cask "cameracontroller"
cask "discord"
cask "google-chrome"
cask "iterm2"
cask "jumpcut"
cask "slack"
cask "spotify"
cask "steam"
cask "visual-studio-code"
cask "zoom"
cask "elgato-control-center"
cask "anki"
cask "affinity-photo"
cask "affinity-designer"
cask "affinity-publisher"
cask "daisydisk"
cask "appcleaner"
cask "font-monaspace-nerd-font"

